// AUTO-GENERATED by scripts/gen-frontend-registry.ts — DO NOT EDIT BY HAND.
// Source of truth: src/registry/agencies.ts (AGENCIES).
// Regenerate with: npm run gen:registry

export type AgencyId = string;

export interface AgencyMeta {
  id: string;
  name: string;
  description: string;
  /** Ordered analyst ids that make up this agency (defines the wall order). */
  analysts: string[];
  /** true for the one default agency (cannot be deleted). */
  isDefault?: boolean;
  /** horizon label for display. */
  horizon?: string;
  instrument?: 'EQUITY' | 'OPTION';
  /** Asset class this agency screens (EQUITY / OPTION / CRYPTO). */
  assetClass?: 'EQUITY' | 'OPTION' | 'CRYPTO';
  /** Explicit screener bar interval (optional — derived from horizon if unset). */
  screenerInterval?: '1m' | '5m' | '1h' | '4h' | '1d';
  /** Explicit screener lookback in days (optional — derived from horizon if unset). */
  screenerLookbackDays?: number;
  /** Minimum average DAILY bar volume (shares) the agency screens for. */
  minVolumeDaily?: number;
  /** True when gated off by default (env ENABLE_CRYPTO_AGENCY to reveal). */
  hidden?: boolean;
}

// Static defaults — overwritten by applyRegistryAgencies() at runtime (hydrated
// from GET /registry). Generated from the backend AGENCIES registry.
export const AGENCIES: Record<string, AgencyMeta> = {
  "long-term": {
    id: "long-term",
    name: "Long-Term Investment",
    description: "Full 7-node pipeline for long-term equity analysis. Matches the current production pipeline exactly — each analyst uses its default fn handler with long-term horizons.",
    analysts: ["orchestrator","data_ingestion","fundamental","technical","sentiment","bull_researcher","bear_researcher","risk","governance"],
    isDefault: true,
    horizon: "LONG_TERM",
    assetClass: "EQUITY",
    screenerInterval: "1d",
    screenerLookbackDays: 90,
    minVolumeDaily: 100000,
  },
  "medium-term": {
    id: "medium-term",
    name: "Medium-Term (1–3 mo)",
    description: "Same 7 analysts but each carries timeHorizon=MEDIUM_TERM via params, demonstrating config reuse without new ids or code.",
    analysts: ["orchestrator","data_ingestion","fundamental","technical","sentiment","bull_researcher","bear_researcher","risk","governance"],
    horizon: "MEDIUM_TERM",
    assetClass: "EQUITY",
    screenerInterval: "4h",
    screenerLookbackDays: 45,
    minVolumeDaily: 100000,
  },
  "intraday": {
    id: "intraday",
    name: "Intraday",
    description: "Same 7 analysts tuned for 5m–1h horizons. Technical gets faster lookback, sentiment is high-frequency, and every analyst carries horizon=INTRADAY.",
    analysts: ["orchestrator","data_ingestion","fundamental","technical","sentiment","bull_researcher","bear_researcher","risk","governance"],
    horizon: "INTRADAY",
    assetClass: "EQUITY",
    screenerInterval: "5m",
    screenerLookbackDays: 5,
    minVolumeDaily: 100000,
  },
  "crypto-screener": {
    id: "crypto-screener",
    name: "Crypto Screener",
    description: "4-node agency proving the framework supports a different NODE COUNT and completely DIFFERENT nodes: a brand-new declarative onchain analyst + reused ingestion/sentiment/governance. Short-horizon crypto triage. (Crypto universe source is TBD — the screener falls back to the equity universe today.)",
    analysts: ["data_ingestion","onchain","sentiment","governance"],
    horizon: "SHORT_TERM",
    assetClass: "CRYPTO",
    screenerInterval: "1d",
    screenerLookbackDays: 90,
    minVolumeDaily: 100000,
    hidden: true,
  },
  "options-swing": {
    id: "options-swing",
    name: "Options Swing (days–weeks)",
    description: "Calendar/diagonal/simple vertical structures on a multi-day to multi-week horizon. Emphasizes IV rank/skew edge + thematic direction; slower greeks (theta is a slow bleed, vega matters). Instrument: OPTION.",
    analysts: ["orchestrator","options_ingestion","vol_surface","options_pricing","options_greeks","options_flow","options_risk","governance"],
    horizon: "MEDIUM_TERM",
    instrument: "OPTION",
    assetClass: "OPTION",
    screenerInterval: "1d",
    screenerLookbackDays: 90,
    minVolumeDaily: 100000,
  },
  "options-intraday": {
    id: "options-intraday",
    name: "Options Intraday (minutes–hours)",
    description: "0DTE / same-day structures, gamma scalping, fast underlying technical timing. Emphasizes tight liquidity, fast theta, intraday vol expansion; strict risk (no overnight gap, strict stop). Instrument: OPTION.",
    analysts: ["orchestrator","options_ingestion","options_technical","vol_surface","options_pricing","options_greeks","options_flow","options_risk","governance"],
    horizon: "INTRADAY",
    instrument: "OPTION",
    assetClass: "OPTION",
    screenerInterval: "5m",
    screenerLookbackDays: 5,
    minVolumeDaily: 100000,
  },
};;

export const AGENCY_IDS: string[] = ["long-term","medium-term","intraday","crypto-screener","options-swing","options-intraday"];

export const DEFAULT_AGENCY: AgencyId = "long-term";

export function agencyById(id: string): AgencyMeta {
  const found = AGENCIES[id];
  if (!found) throw new Error(`Unknown agency: ${id}`);
  return found;
}
